LOG:  00000: statement: create function excpt_test3() returns void as $$  begin  begin  raise exception 'user exception';  exception when others then  raise notice 'caught exception % %', sqlstate, sqlerrm;  begin  raise notice '% %', sqlstate, sqlerrm;  perform 10/0;  exception  when substring_error then  -- this exception handler shouldn't be invoked  raise notice 'unexpected exception: % %', sqlstate, sqlerrm;  when division_by_zero then  raise notice 'caught exception % %', sqlstate, sqlerrm;  end;  raise notice '% %', sqlstate, sqlerrm;  end;  end; $$ language plpgsql;
LOCATION:  exec_simple_query, postgres.c:938
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
LOCATION:  exec_stmt_raise, pl_exec.c:3216
STATEMENT:  create function excpt_test3() returns void as $$  begin  begin  raise exception 'user exception';  exception when others then  raise notice 'caught exception % %', sqlstate, sqlerrm;  begin  raise notice '% %', sqlstate, sqlerrm;  perform 10/0;  exception  when substring_error then  -- this exception handler shouldn't be invoked  raise notice 'unexpected exception: % %', sqlstate, sqlerrm;  when division_by_zero then  raise notice 'caught exception % %', sqlstate, sqlerrm;  end;  raise notice '% %', sqlstate, sqlerrm;  end;  end; $$ language plpgsql;
ERROR:  42601: syntax error at end of input at character 537
LOCATION:  plpgsql_yyerror, pl_scanner.c:623
STATEMENT:  create function excpt_test3() returns void as $$  begin  begin  raise exception 'user exception';  exception when others then  raise notice 'caught exception % %', sqlstate, sqlerrm;  begin  raise notice '% %', sqlstate, sqlerrm;  perform 10/0;  exception  when substring_error then  -- this exception handler shouldn't be invoked  raise notice 'unexpected exception: % %', sqlstate, sqlerrm;  when division_by_zero then  raise notice 'caught exception % %', sqlstate, sqlerrm;  end;  raise notice '% %', sqlstate, sqlerrm;  end;  end; $$ language plpgsql;
